### ISSUE TITLE
关于主题的一些疑问

### ISSUE THREAD

**Issue by ghost** [Troy-Yang/hexo-theme-twentyfifteen-wordpress#3]
左侧边栏內容溢出部分看不到
右下角那个放回顶部图标下面的 top 文字怎么去掉 css里找不到

**Comment by xzy997** [comment]
是否忘記刪除？
![](https://ws1.sinaimg.cn/large/005CKhK0ly1fqmr9zdpcrj309m05yjru.jpg)

**Comment by Troy-Yang** [comment]
左侧边栏溢出你指的是浏览器高度不够导致有些内容板块，如标签云等看不到？是的话，有空加上个好看些的垂直滚动条。

top那个请修改hexo-theme-twentyfifteen-wordpress/layout/_partial/components/back-top.ejs

欢迎提出其他改进意见

**Comment by ghost** [comment]
@Troy-Yang 
侧边栏问题好像其他主题也是这样，加滚动条不好看。。
请问如何解决百度等搜索引擎爬不到博客文章的问题。知乎上看到有答主说coding因为广告跳转已经不行了。
感谢提供解答。

**Comment by Troy-Yang** [comment]
试试hexo baidu_url_submit plugin, 我用的就是这个，这个可以主动推送到百度搜索引擎，效果比百度自己爬要好得多。

**Comment by ghost** [comment]
@Troy-Yang 十分钟抱歉 再次打扰。 leancloud 弄的文章阅读数的功能，我设置后，阅读数到1就不会再变，打开文章也也不会显示阅读数数字。让朋友测试也是一样，按照网上的方法配置的。请问是否此主题配置方法有差异？

**Comment by ghost** [comment]
问题已解决。在leancloud上改了权限后就正常了。主题很好看。感谢您的帮助

**Comment by Troy-Yang** [comment]
不客气的，谢谢喜欢，欢迎提出改进意见或者疑问
