### ISSUE TITLE
主题求更新

### ISSUE THREAD

**Issue by ghost** [Troy-Yang/hexo-theme-twentyfifteen-wordpress#5]
内置的js和网上教程的不同，不知道如何修改。[主题搜索功能优化](https://github.com/wzpan/hexo-generator-search/issues/46)

valine评论系统[valine](https://valine.js.org)。valine和主题内置的文章阅读统计冲突，能否兼容valine自带的文章阅读统计
@Troy-Yang

**Comment by Troy-Yang** [comment]
你指的主题搜索功能那个具体是什么问题？是这个主题的search功能和hexo-generator-search插件使用方式不同吗？

至于valine评论系统，因为暂时没去支持，如果你想要支持的话，你可以fork这个主题，然后，修改下面两个文件，改为调用你那个评论系统的api：

https://github.com/Troy-Yang/hexo-theme-twentyfifteen-wordpress/blob/master/layout/_partial/analytics/leancloud.ejs 

https://github.com/Troy-Yang/hexo-theme-twentyfifteen-wordpress/blob/master/layout/_partial/components/visitor.ejs
